<?php


namespace App\Services\Admin;


use App\Models\Product;
use App\Models\Category;
use App\Validators\Admin\ProductValidator;
use App\Services\BaseService;

/**
 * Class ProductService
 * @package App\Services\Admin
 */
class ProductService extends BaseService
{
    /**
     * @return string
     */
    protected function getModelClass(): string
    {
        return Product::class;
    }

    /**
     * @return string
     */
    protected function getValidatorClass(): string
    {
        return ProductValidator::class;
    }

    /**
     * @return mixed
     */
    public function categoryTree()
    {
        return Category::all();
    }

    /**
     * @param array $params
     * @return Object
     */
    public function paginated($params = []): object
    {
        return parent::paginated(['with' => 'category']);
    }

    /**
     * @param $id
     * @param null $relations
     * @return object
     */
    public function getSingle($id, $relations = null): object
    {
        return parent::getSingle($id, ['category']); // TODO: Change the autogenerated stub
    }
}
